name: swayze_example
description: An example for Swayze
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_sticky_header: ^0.6.0
  swayze:
    path: ../
  equatable: ^2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  rows_lint: 0.1.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
