name: swayze_math
description: Classes for math operations in the context of a spreadsheet UI
version: 1.1.0
repository: https://github.com/rows/swayze
issue_tracker: https://github.com/rows/swayze/issues
homepage: https://github.com/rows/swayze


environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.16.8
  rows_lint: 0.1.1
  dartdoc: ^2.0.0