name: swayze_math
description: Classes for math operations in the context of a spreadsheet UI
version: 1.2.0
repository: https://github.com/rows/swayze
issue_tracker: https://github.com/rows/swayze/issues
homepage: https://github.com/rows/swayze


environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  collection: ^1.18.0 

dev_dependencies:
  test: ^1.25.0
  rows_lint: 0.1.1
  dartdoc: ^6.3.0