name: pull-request

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Setup melos
        uses: bluefireteam/melos-action@main

      - name: Check format
        run: melos run format-check

  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Setup Melos
        uses: bluefireteam/melos-action@main

      - name: Analyze
        run: melos run analyze

  publish-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Setup Melos
        uses: bluefireteam/melos-action@main

      - name: Publish dry run
        run: melos publish --dry-run -y

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: stable

      - name: Setup Melos
        uses: bluefireteam/melos-action@main

      - name: Run tests
        run: melos run test

      - name: Upload test packages artifacts
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: packages-test-artifacts
          path: |
            packages/**/test/**/failures/

      - name: Run golden tests
        run: melos run test-update-goldens
        if: failure()
        
      - name: Upload test packages artifacts updated
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: packages-test-artifacts-updated
          path: |
            packages/**/test/**/goldens/